

const mongoose = require("mongoose");

const gameDataSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: "User" },

  userChoice: { type: String }, // Big or Small
  userChoiceAmount: { type: Number },

  userColor: { type: String }, // Red, Green, Purple
  colorAmount: { type: Number },

  userNumber: { type: Number },
  numberAmount: { type: Number },

  // Generated by backend
  randomChoiceNumber: Number,
  randomChoiceColor: String,
  randomChoiceBigSmall: String,

  result: String,
  winAmount: Number,
  period: String,

  createdAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model("GameData", gameDataSchema);
